### ISSUE TITLE
'ts-req-selector="children ul"' doesn't activate children elements

### ISSUE THREAD

**Issue by last-arg** [piranha/twinspark-js#26]
**Example:**
```html
<div ts-req="<url>" ts-trigger="load" ts-swap="replace" ts-req-selector="children ul"></div>
```

**Problem:**
When using 'ts-req-selector="children ul"' for swapping it will use DocumentFragment. But during swap DocumentFragment will become empty. This means activate() function will be called on DocumentFragment with no children - no elements will be activated. And 'ts-ready' event will not fire.

Not sure if it is wanted behaviour or not?

**Comment by piranha** [comment]
Ah, that's a bug, thanks for heads up! Dammit I knew DocumentFragment will trip me somewhere, they always do. 😁

I'll look into that later on - or you can take a swing at it if you want. :)
